version: "3.9"
services:
  postgres:
    container_name: db-postgres
    image: postgres:14.8-alpine3.18
    command: [ "postgres", "-c", "config_file=/etc/postgresql.conf" ]
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - ./docker/postgresql.conf:/etc/postgresql.conf
      - ./docker/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
  redis:
    container_name: cache-redis
    image: redis/redis-stack:7.2.0-v4
    volumes:
      - ./docker/data/redis:/data
      - ./docker/redis.conf:/redis-stack.conf
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
      - "13333:8001"
    restart: unless-stopped
