version: "3.9"
services:
  bot:
    build:
      context: .
    container_name: tg-note-bot
    hostname: tg-note-bot
    env_file:
      - .env
    volumes:
      - ./data/logs:/app/data/logs
      - ./data/db:/app/data/db
      - ./data/${DB_DATABASE}.db:/app/data/${DB_DATABASE}.db
    restart: unless-stopped
#  postgres:
#    container_name: db-postgres
#    image: postgres:14.8-alpine3.18
#    command: [ "postgres", "-c", "config_file=/etc/postgresql.conf" ]
#    environment:
#      POSTGRES_DB: "${DB_DATABASE}"
#      POSTGRES_USER: "${DB_USER}"
#      POSTGRES_PASSWORD: "${DB_PASS}"
#      PGDATA: /var/lib/postgresql/data/db-files/
#    volumes:
#      - ./config/postgresql.conf:/etc/postgresql.conf
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: 4G
  redis:
    container_name: tg-note-bot-cache-redis
    hostname: tg-note-bot-cache-redis
    image: redis/redis-stack:7.2.0-v4
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis-stack.conf
    env_file:
      - .env
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
