"""Add attachments

Revision ID: de88ab5c06ea
Revises: 13495f23fad1
Create Date: 2024-04-09 16:26:27.267367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de88ab5c06ea"
down_revision: Union[str, None] = "13495f23fad1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usernotes", sa.Column("file_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usernotes", "file_id")
    # ### end Alembic commands ###
